// Hook for using custom presets
import { useMemo } from 'react';
import { useTheme } from '@mui/material/styles';
import { PresetBuilder } from '../core/PresetBuilder';

/**
 * Apply a custom preset to the current theme
 * @param preset PresetBuilder instance with your custom styling
 * @returns Theme options generated by the preset
 */
export const usePreset = (preset: PresetBuilder) => {
  const theme = useTheme();

  return useMemo(() => {
    return preset.build(theme);
  }, [preset, theme]);
};
